# Generated by Django 3.1 on 2020-08-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinRegModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitted', models.BooleanField(default=False)),
                ('intercept', models.FloatField(default=0)),
                ('coef_distance', models.FloatField(default=0)),
                ('coef_uphill', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('illustration', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_visited', models.DateField(blank=True, null=True)),
                ('is_recording', models.BooleanField(default=False)),
                ('is_itinerary', models.BooleanField(default=False)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('uphill', models.FloatField(blank=True, null=True)),
                ('downhill', models.FloatField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('gpx', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WaypointCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('label', models.CharField(max_length=255)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('visited', models.BooleanField(default=False)),
                ('date_visited', models.DateField(blank=True, null=True)),
                ('illustration', models.URLField(blank=True, null=True)),
                ('chaine_des_puys', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topopartner.waypointcategory')),
            ],
        ),
    ]
