# Generated by Django 4.2.5 on 2023-12-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topopartner', '0003_auto_20210118_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypointcategory',
            name='user',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='linregmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Waypoint',
        ),
        migrations.DeleteModel(
            name='WaypointCategory',
        ),
    ]
