# Generated by Django 4.1.7 on 2023-12-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topopartner', '0004_remove_waypointcategory_user_alter_apikey_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='is_itinerary',
            new_name='is_route',
        ),
    ]
